// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-10-29 02:56:32.8233575 +0800 CST m=+0.104204201

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "info": {
        "contact": {},
        "license": {}
    },
    "paths": {
        "/admin/v1/shop/ashop": {
            "post": {
                "description": "add by json ReqShopInfo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "添加商品",
                "parameters": [
                    {
                        "description": "商品信息",
                        "name": "shop_info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ShopInfo"
                        }
                    },
                    {
                        "description": "款式",
                        "name": "shop_style",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ShopStyle"
                        }
                    },
                    {
                        "description": "款式图片",
                        "name": "img_style",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Image"
                        }
                    },
                    {
                        "description": "商品图片",
                        "name": "img_shop",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Image"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"data\":null,\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/v1/upload": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "上传图片",
                "parameters": [
                    {
                        "type": "file",
                        "description": "图片文件",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"data\":{\"img_save_url\":\"upload/images/8f81dcf6-b970-4ed1-bd02-ccf1c908c0f1.jpg\",\"img_url\":\"localhost:5054/upload/images/8f81dcf6-b970-4ed1-bd02-ccf1c908c0f1.jpg\"},\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mobile/v1/shop/type": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取分类信息",
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"msg\":\"ok\",\"shop_type\":{\"id\":2,\"parent_id\":0,\"c_name\":\"测试2\",\"r_name\":\" тест 2\",\"created_at\":\"14:57:22\",\"update_at\":\"14:57:27\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Image": {
            "type": "object",
            "required": [
                "img_type",
                "img_url"
            ],
            "properties": {
                "create_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "img_name": {
                    "type": "string"
                },
                "img_type": {
                    "type": "integer"
                },
                "img_url": {
                    "type": "string"
                },
                "target_id": {
                    "type": "integer"
                }
            }
        },
        "model.ShopInfo": {
            "type": "object",
            "required": [
                "contact_info",
                "contact_type",
                "shop_name",
                "type_id"
            ],
            "properties": {
                "contact_info": {
                    "type": "string"
                },
                "contact_type": {
                    "type": "integer"
                },
                "create_at": {
                    "type": "string"
                },
                "discount_price": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "market_price": {
                    "type": "number"
                },
                "shop_describe": {
                    "type": "string"
                },
                "shop_name": {
                    "type": "string"
                },
                "sort_weight": {
                    "type": "integer"
                },
                "type_id": {
                    "type": "integer"
                },
                "update_at": {
                    "type": "string"
                }
            }
        },
        "model.ShopStyle": {
            "type": "object",
            "required": [
                "style_name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "shop_id": {
                    "type": "integer"
                },
                "style_describe": {
                    "type": "string"
                },
                "style_name": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
